name: Dependabot Action All

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Dependabot Action'
        required: true
        default: 'warning'
        type: choice
        options:
        - rebase
        - recreate
        - merge
        - squash and merge
        - cancel merge
        - reopen
        - close
        - ignore this major version
        - ignore this minor version
        - ignore this dependency

jobs:
  rebase:
    uses: austenstone/.github/.github/workflows/dependabot-rebase-all.yml@main
    with:
      action: ${{ inputs.action }}
